export enum UnitSubType {
  APARTMENT = 'APARTMENT',
  VILLA = 'VILLA',
  TOWNHOUSE = 'TOWNHOUSE',
  PENTHOUSE = 'PENTHOUSE',
  OFFICE_SPACE = 'OFFICE_SPACE',
  RETAIL_STORE = 'RETAIL_STORE',
  WAREHOUSE = 'WAREHOUSE',
  LAND_PLOT = 'LAND_PLOT',
}
